### ISSUE TITLE
Device maintenance 

### ISSUE THREAD

**Issue by soulremover** [Magisk-Modules-Repo/crokrammgmtfix#1]
Does device maintenance from Samsung erase/restore these changes back to default ?

**Comment by crok** [comment]
Since it does not need root access I presume it cannot change anything
related to the module and the preferences it has changed.

**Comment by soulremover** [comment]
That's cool. What if i want to uninstall the module ? How can i do it, will it reset all the values back to default ? 
Thanks for the fast reply mate. Keep up the good work !

**Comment by crok** [comment]
You can uninstall it via the Magisk Manager, that's the most common and easiest method - or, if you go to TWRP, push install and browse and run this zip (https://forum.xda-developers.com/apps/magisk/collection-magisk-modules-v2-t3575758/post72327720#post72327720) this will mount the Magisk directory to /magisk when you are still in the recovery (does not install anything, just mount Magisk to /mount) and if you have Aroma filemanager in TWRP or use RedWolf recovery (https://forum.xda-developers.com/redmi-note-4/xiaomi-redmi-note-4-snapdragon-roms-kernels-recoveries--other-development/recovery-red-wolf-recovery-project-t3653704) instead of TWRP then you can easily delete the directory of the module from /magisk and you just manually uninstalled the module. This works for any Magisk Module. Probably it would seem to be complicated, but when you do it it is easy as 123..  ( :

**Comment by soulremover** [comment]
explained perfectly !! i am familiar with both ways !! Thanks a lot for the help ! I will give it a try !
Keep up the good work mate.
